name: _Reusable Nx template

on:
  workflow_call:
    inputs:
      nx-head:
        type: string
        description: Commit SHA, branch or tag name used by Nx in the affected jobs as head.
        required: true
      nx-base:
        type: string
        description: Commit SHA, branch or tag name used by Nx in the affected jobs as base.
        required: true
        default: next
      nx-skip-cache:
        type: boolean
        description: Rerun the tasks even when the results are available in the cache.
        default: false
      nx-force-all:
        type: boolean
        description: Forces Nx to consider all projects (apps and libs) as affected.
        default: false
    outputs:
      affected-apps:
        description: Nx applications affected by the changes
        value: ${{ jobs.nx.outputs.affected-apps }}
      affected-lib:
        description: Nx libraries affected by the changes
        value: ${{ jobs.nx.outputs.affected-lib }}
      affected-e2e:
        description: Nx e2e projects affected by the changes
        value: ${{ jobs.nx.outputs.affected-e2e }}
      affected-package-container:
        description: Nx projects configured with package:container affected by the changes
        value: ${{ jobs.nx.outputs.affected-package-container }}
      affected-deploy-static:
        description: Nx projects configured with deploy:static affected by the changes
        value: ${{ jobs.nx.outputs.affected-deploy-static }}
      affected-deploy-container:
        description: Nx projects configured with deploy:container affected by the changes
        value: ${{ jobs.nx.outputs.affected-deploy-container }}

permissions:
  contents: read # Minimal required permission

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
  NX_BRANCH: ${{ github.event.workflow_run.head_branch }}
  BRANCH: ${{ github.event.workflow_run.head_branch }}
  NX_FORCE_ALL: ${{ fromJSON('["", "--all"]')[ inputs.nx-force-all ] }} # This relies on type coercion, an implicit cast from boolean true to 1 or false to 0, which is then used as array index.
  NX_SKIP_NX_CACHE: ${{ inputs.nx-skip-cache || false }}

jobs:
  nx:
    name: Nx Affected
    runs-on: ubuntu-22.04
    outputs:
      affected-apps: ${{ steps.configure-nx.outputs.affected-apps }}
      affected-lib: ${{ steps.configure-nx.outputs.affected-lib }}
      affected-e2e: ${{ steps.configure-nx.outputs.affected-e2e }}
      affected-package-container: ${{ steps.configure-nx.outputs.affected-package-container }}
      affected-deploy-static: ${{ steps.configure-nx.outputs.affected-deploy-static }}
      affected-deploy-container: ${{ steps.configure-nx.outputs.affected-deploy-container }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.nx-head }}
          filter: blob:none

      - uses: nrwl/nx-set-shas@v4
        if: inputs.nx-force-all == false
        with:
          main-branch-name: ${{ inputs.nx-base }}

      - name: Setup Bun Runtime
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: 1.0.15

      - name: Cache
        id: cache
        uses: actions/cache@v4
        env:
          cache-name: cache
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          path: |
            ~/.bun/install/cache

      - name: Install Dependencies
        run: bun install

      - name: Evaluate affected projects
        id: configure-nx
        run: |
          if [ "$NX_FORCE_ALL" = "--all" ]; then
            echo affected-apps=$(bunx nx show projects --type=app --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-lib=$(bunx nx show projects --type=lib --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-e2e=$(bunx nx show projects --with-target=e2e --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-package-container=$(bunx nx show projects --with-target=package:container --type=app --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-deploy-static=$(bunx nx show projects --with-target=deploy:static --type=app --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-deploy-container=$(bunx nx show projects --with-target=deploy:container --type=app --json | jq -c '. // []') >> $GITHUB_OUTPUT
          else
            echo affected-apps=$(bunx nx show projects --affected --type=app --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-lib=$(bunx nx show projects --affected --type=lib --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-e2e=$(bunx nx show projects --affected --with-target=e2e --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-package-container=$(bunx nx show projects --affected --with-target=package:container --type=app --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-deploy-static=$(bunx nx show projects --affected --with-target=deploy:static --type=app --json | jq -c '. // []') >> $GITHUB_OUTPUT
            echo affected-deploy-container=$(bunx nx show projects --affected --with-target=deploy:container --type=app --json | jq -c '. // []') >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT | grep affected
